### ISSUE TITLE
[Fix] QA 에러 수정

### ISSUE THREAD

**Issue by chmini** [prgrms-fe-devcourse/FEDC2_CheQuiz_Gidong#116]
## ✏️ 작업 내용

**Header**
- [x]  로그아웃 기능 추가 `창민`
- [x]  알림 없을 때 표시 `창민`
- [x]  알림 생성 기능 추가 (댓글 및 좋아요 생성 시) `창민`

**Main**
- [x]  width 상수 값 제거 `인수`

**Rank**
- [x]  랭킹페이지 border 제거 `인수`
- [x]  크기 적절히 조절 `인수`
- [x]  cursor pointer추가 `인수`

**QuizCreate**
- [x]  CreateQuiz validation 디자인 `인수`

**QuizSolve**
- [x]  문제번호 크게 `인수`
- [x]  background 회색 `인수`
    - 이거는 width:100% height:100% position:fixed 로 놓으면 될거에요..!

**Result**
- [x]  댓글 box border 삭제, background(#E9ECEF), input(white) 추가 `준혁`
- [x]  코멘트 작성하기 삭제, comment 보기 ⇒ 댓글 보기 `준혁`
- [x]  댓글 쓰기 버튼 height를 input에 맞추기 `준혁`
- [x]  좋아요 text 대신 ⇒ 좋아요 클릭 시 fill 따봉 / 취소 시 투명 따봉 `준혁`
- [x]  toggle ⇒ 아이콘으로 변경 `준혁`
- [x]  각 퀴즈의 댓글 버튼 눌러도 toggle 열리도록 함수 추가 `준혁`
- [x]  토글 아이콘 변경 `준혁`
- [x]  하단 버튼 디자인 변경 `준혁`

**UserInfo**

- [x]  처음 진입 시 가입자 정보가 없습니다 수정 `준혁`

**기타**
- [x] env 적용

## ⏰ 예상 시간

1D

## 🔎 추가 정보

- QA 진행
